container:
  image: node:latest

test_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install

  matrix:
    - name: Format
      check_script: yarn run checkFormat
    - name: Lint
      lint_script: yarn run lint
    - name: Test
      test_script: yarn run test
    - name: Coverage
      coverage_script: yarn run coveralls
